language: python
python: "3.6"
install: pip install -r test_requirements.txt
script: 
- pytest -v bin/2018_07_11_pca_te_enhancers/test_shuffled_pca.py
- pytest -v bin/2018_07_12_pca_te_enhancers/test_reformat_df.py
- pytest -v bin/2018_07_13_pca_te_enhancers/test_shuffled_pca.py
- pytest -v bin/2018_07_13_pca_te_enhancers/test_pca.py
- pytest -v bin/2018_07_16_tsne_kmers/test_pca.py
- pytest -v bin/2018_07_17_tsne_kmers/test_pca.py
- pytest -v bin/2018_07_17_tsne_kmers/test_sampling.py
- pytest -v bin/2018_07_20_random_sets/test_data_splitter.py
- pytest -v bin/2018_07_23_random_sets/test_kmer_counter.py